name: client_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  device_preview: ^1.2.0
  flutter_gen: ^5.8.0
  build_runner: ^2.4.13
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  flutter_localization: ^0.2.2
  font_awesome_flutter: ^10.7.0
  pinput: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter_rating_bar: ^4.0.1
  easy_stepper: ^0.8.5+1
  dio: ^5.7.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  pretty_dio_logger: ^1.4.0
  lottie: ^3.1.3
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.1.4
  easy_autocomplete: ^1.6.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  google_sign_in: ^6.2.2
  webview_flutter: ^4.10.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/cofee.png"
  macos:
    generate: true
    image_path: "assets/images/png/cofee.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/lottie/
    - assets/lang/en.json
    - assets/lang/ar.json
  fonts:
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
